CustomVocabLoader tests
thehyve/delphyne pull request #148
Opened 2021-02-17 16:03 UTC by alepev

Fixes #54

2021-03-10 15:52 UTC, alepev commented
Tests complete, now starting refactoring to use delegation pattern in `CustomVocabLoader` instead of inheritance

2021-03-10 17:15 UTC, alepev commented on tests/python/model/custom_vocab/test_custom_vocab_loader.py
> +        assert loaded_classes == ['CLASS1_v2', 'CLASS2_v2']
So we agree with this behavior? At the moment file prefixes are kind of ignored when loading custom vocabularies and classes (though for vocabularies, you do get a warning of the vocabulary_id is different than the prefix). We might want to make it more strict and completely skip the file is the prefix does not match a vocabulary_id to be updated.

2021-03-10 17:16 UTC, alepev commented on tests/python/model/custom_vocab/test_custom_vocab_loader.py
> +        assert loaded_concepts == [2000000001, 2000000002, 2000000005]
...and here is the stricter concept behavior

2021-03-26 12:06 UTC, Spayralbe requested changes
The missing `continue` issue should be fixed (maybe also validate in a test that a <2B concept will not be committed), but otherwise great additions!

2021-03-26 12:47 UTC, Spayralbe commented on src/delphyne/model/custom_vocab/base_manager/concept_manager.py
>                      if vocabulary_id in vocab_ids:
Could be useful to also log a warning when an unknown vocabulary_id (not present in any vocabulary.tsv file) is encountered in a concept file. Now they are silently ignored.

2021-03-26 13:01 UTC, Spayralbe commented on tests/python/model/custom_vocab/test_custom_vocab_loader.py
> +        assert loaded_classes == ['CLASS1_v2', 'CLASS2_v2']
I think it's ok like this. Relation-wise the concept classes are not specific to a vocabulary anyway.

2021-04-12 10:19 UTC, alepev commented on src/delphyne/model/custom_vocab/base_manager/class_manager.py
> +                        f'{ignored_classes}')
agreed, updated here and in vocab_manager. updated tests to use debug-level caplog.

2021-04-12 10:20 UTC, alepev commented on src/delphyne/model/custom_vocab/base_manager/concept_manager.py
>                      if vocabulary_id in vocab_ids:
Added warning and updated tests

2021-04-12 10:20 UTC, alepev commented on src/delphyne/model/custom_vocab/base_manager/concept_manager.py
> +                        file_errors = True
That was a big omission, thanks for spotting!

2021-04-12 10:24 UTC, alepev commented on src/delphyne/model/custom_vocab/base_manager/concept_manager.py
> +class ConceptManager:
Referenced in new issue. Agreed that is not ideal, but will pass on it for now (low priority).

2021-04-12 10:52 UTC, alepev commented
OK I'm done now, I had forgotten to update the docs with how we process file prefixes

2021-04-12 16:16 UTC, Spayralbe approved these changes
🎍

2021-04-12 18:23 UTC, alepev commented
🤩

2021-04-12 18:23 UTC, merged