Short transformations guide
thehyve/delphyne pull request #155
Opened 2021-02-19 17:31 UTC by MaximMoinat

Closes #145 

Have not tested the rst syntax.

2021-02-23 09:33 UTC, alepev commented on docs/transformations.rst
> +By extending the :mod:`~src.delphyne.wrapper.Wrapper` a number of transformation functions are available.
you can replace this and other occurrences with :class:`.Wrapper`, it will work :)

2021-02-23 09:34 UTC, alepev commented on docs/transformations.rst
> +The first mode, used by :mod:`~src.delphyne.wrapper.Wrapper.execute_transformation`.
..and this with :meth:`~.Wrapper.execute_transformation()`

2021-02-23 09:43 UTC, alepev commented on docs/transformations.rst
> +By extending the :mod:`~src.delphyne.wrapper.Wrapper` a number of transformation functions are available.
btw: "by extending the Wrapper" sounds a bit weird. I would say that the Wrapper offers different ways to execute transformation scripts?

2021-02-23 09:44 UTC, alepev commented on docs/transformations.rst
> +For both options the :mod:`~src.delphyne.wrapper.Wrapper` has build-in methods that coordinate the execution.
builT-in (if you keep this sentence, maybe not needed)

2021-02-23 09:45 UTC, alepev commented on docs/transformations.rst
> +These methods, detailed below, use SqlAlchemy to handle database operations and log the execution statistics.
the capitalization is "SQLAlchemy"

2021-02-23 09:45 UTC, alepev commented on docs/transformations.rst
> +These methods, detailed below, use SqlAlchemy to handle database operations and log the execution statistics.
Same for "SQL" below

2021-02-23 09:47 UTC, alepev commented on docs/transformations.rst
> +See delphyne-template for examples.
It could be useful to link to the template repository here, specifically the `transformations` folder

2021-02-23 09:48 UTC, alepev commented on docs/transformations.rst
> +These methods, detailed below, use SqlAlchemy to handle database operations and log the execution statistics.
(Check other occurrences too, it's a minor thing really but should be consistent). 
Another one I noticed: capitalization of Python (sometimes written lowercase, sometimes uppercase)

2021-02-23 09:51 UTC, alepev commented on docs/transformations.rst
> +See delphyne-template for examples.
Actually, it might be good to add specific instructions on where to place the transformations in the template:
- for ORM-based: `src/main/python/transformation`
- for SQL-based: `src/main/sql`

2021-02-23 09:53 UTC, alepev commented on docs/transformations.rst
> + it is good practice to create a separate file for each table to table transformation.
This part is true for all transformations, move at the top before going into the details of ORM vs SQL

2021-02-23 09:54 UTC, alepev commented on docs/transformations.rst
> +The first mode, used by :mod:`~src.delphyne.wrapper.Wrapper.execute_transformation`.
it works irrespectively, it's just shorter if you need to edit it later in the raw .rst file

2021-02-23 09:57 UTC, alepev commented on docs/transformations.rst
> +```
I suggest providing separate explicit examples for the case with return and yield, and add blocks showing how you would execute the corresponding transformation with either `execute_transformation` or `execute_batch_transformation` in the Wrapper. I think you can use of the the OMOP tables explicitly, say `Person`

2021-02-23 09:58 UTC, alepev commented on docs/transformations.rst
> +def my_transformation(wrapper):
You need an empty line between the text and the start of the code block, otherwise it doesn't display correctly. Also between `python` and the first line of code.

2021-02-23 10:03 UTC, alepev commented on docs/transformations.rst
> +```
same here, you will need something like `.. code-block:: sql` (see if it works, I haven't tried that one)

2021-02-23 10:03 UTC, alepev commented on docs/transformations.rst
> +INSERT INTO @cdmSchma.<target_table> (
typo in `@cdmSchema`

2021-02-23 10:04 UTC, alepev commented on docs/transformations.rst
> +SQL queries can easily be executed with through the wrapper.
"with" or "through"

2021-02-23 10:11 UTC, alepev commented on docs/transformations.rst
> +INSERT INTO @cdmSchma.<target_table> (
actually, the placeholder name should be `@cdm_schema`. this will be taken straight from the `schema_translate_map` section in the configuration file

2021-02-23 10:12 UTC, alepev commented on docs/transformations.rst
> +FROM @sourceSchema.<source_table>
I was wondering if we could give an example where the data is read from file rather than from another schema, since that's our main use case.

2021-02-23 10:19 UTC, alepev reviewed
Good start, needs some fixes. Btw, if you want to see the result, run `nox -s docs`, then head to `docs/_build` and open `index.html`. IntelliJ should show you some browser icons in the upper right corner. (Otherwise: right-click > Open in > Browser)

2021-02-23 10:24 UTC, alepev commented on docs/transformations.rst
> +If the sql query is saved in a file, the method :mod:`~src.delphyne.wrapper.Wrapper.execute_sql_file` is used.
Also in this case, could be good to write out an example. There is a difference with `execute_transformation()`, that is the full SQL file name has to written out explicitly as a string (e.g. `execute_sql_file('my_file.sql'`))

2021-03-15 12:08 UTC, MaximMoinat commented on docs/transformations.rst
> +By extending the :mod:`~src.delphyne.wrapper.Wrapper` a number of transformation functions are available.
Well, extending this class is what you do right?
```python
class my_wrapper(delphyne.Wrapper):
    ...
```

2021-03-15 12:10 UTC, MaximMoinat commented on docs/transformations.rst
> +By extending the :mod:`~src.delphyne.wrapper.Wrapper` a number of transformation functions are available.
Will still use your suggestion :)

2021-03-15 12:11 UTC, MaximMoinat commented on docs/transformations.rst
> +The first mode, used by :mod:`~src.delphyne.wrapper.Wrapper.execute_transformation`.
Cool, that is actually very helpful to learn a bit on rst! :D

2021-03-15 13:17 UTC, MaximMoinat commented on docs/transformations.rst
> +FROM @sourceSchema.<source_table>
For pure SQL, that is not our main use case, right?

2021-03-15 13:33 UTC, MaximMoinat commented
Thanks bunches @alepev! I updated the text accordingly

2021-03-16 11:06 UTC, alepev commented on docs/transformations.rst
> +For both options the :class:`.Wrapper` has built-in methods that coordinate the execution.
```suggestion
For all of these options, the :class:`.Wrapper` has built-in methods that coordinate the execution.
```

2021-03-16 11:06 UTC, alepev commented on docs/transformations.rst
> +For both options the :class:`.Wrapper` has built-in methods that coordinate the execution.
(cannot use both with > 2)

2021-03-16 11:08 UTC, alepev commented on docs/transformations.rst
> +It can return these objects in two different ways (see below).
I think you can remove this line, it's says again below that there's 2 ways of executing

2021-03-16 11:09 UTC, alepev commented on docs/transformations.rst
> +This expects the transformation function to return the full list of ORM objects at once.
The first sentence ends strangely with a dot, I think you can merge them ("[...] Wrapper.execute_transformation expects the transformation function..")

2021-03-16 11:11 UTC, alepev commented on docs/transformations.rst
> +            omop_record = wrapper.cdm.Observation(
not sure about that "omop_record".. just "record" or "cdm_record"? :P

2021-03-16 11:12 UTC, alepev commented on docs/transformations.rst
> +In the wrapper these two transformations can be called like this:
Suggestion: in other places we specifically say to add calls to the Wrapper's **run method**, so you could change it to make it very explicit

2021-03-16 11:17 UTC, alepev commented on docs/transformations.rst
> +If the SQL query is saved in a file, the method :meth:`.Wrapper.execute_sql_file` is used.
Also for these, please provide a code block at the end of the paragraph showing how these calls would appear in the wrapper method

2021-03-16 11:18 UTC, alepev commented on docs/transformations.rst
> +The easiest way to create a transformations with sql is by following the template given here.
sql -> SQL (check the file to see if it happens anywhere else)

2021-03-16 11:32 UTC, alepev commented on docs/transformations.rst
> +-------------
the dashes should be the same length as the title

2021-03-16 11:32 UTC, alepev commented on docs/transformations.rst
>  -------------
The dashed should be the same length as the title

2021-03-16 11:32 UTC, alepev commented on docs/transformations.rst
> +---------------
The dashes should be the same length as the title

2021-03-16 11:33 UTC, alepev commented on docs/transformations.rst
> +-------------
The dashes should be the same length as the title

2021-03-16 11:41 UTC, alepev commented on docs/transformations.rst
> + - Write a Python function, creating a query using the `SQLAlchemy expression language <https://docs.sqlalchemy.org/en/14/core/tutorial.html>`_.
```suggestion
    - Write a Python function, returning the results as `SQLAlchemy ORM objects <https://docs.sqlalchemy.org/en/14/orm/tutorial.html>`_.
    - Write a SQL query, directly inserting into the target table.
    - Write a Python function, creating a query using the `SQLAlchemy expression language <https://docs.sqlalchemy.org/en/14/core/tutorial.html>`_.
```

2021-03-16 11:42 UTC, alepev commented on docs/transformations.rst
> + - Write a Python function, creating a query using the `SQLAlchemy expression language <https://docs.sqlalchemy.org/en/14/core/tutorial.html>`_.
This worked fine, but somehow when generating the docs with sphinx I still get a complaint on the indentation level. I made it 4 spaces and the warning is gone.

2021-03-16 11:45 UTC, alepev commented on docs/transformations.rst
> + - Write a Python function, creating a query using the `SQLAlchemy expression language <https://docs.sqlalchemy.org/en/14/core/tutorial.html>`_.
when generating the docs with sphinx I get a complaint, add an empty line before the first bullet point and it will go away

2021-03-16 11:49 UTC, alepev commented on docs/transformations.rst
> + - Write a Python function, creating a query using the `SQLAlchemy expression language <https://docs.sqlalchemy.org/en/14/core/tutorial.html>`_.
Another note: should the links point one step higher, to the ORM/core reference instead of directly to the tutorial?

2021-03-16 11:51 UTC, alepev commented on docs/transformations.rst
> +There are two ways of execution the transformation, each requiring a different return type.
"Two ways of executiNG" ?

2021-03-16 11:55 UTC, alepev commented on docs/transformations.rst
> +The wrapper will commits the yielded records to the database in batches of given size.
Important: add (in parenthesis?) that this is decided via the `batch_size` option

2021-03-16 12:05 UTC, alepev requested changes
Still some changes, but much better!

Actually there are also couple big points I'm missing in the description (which I failed to bring up in the previous review 🤦‍♀️ ): 
- ~we should mention the `bulk_mode` option in the SQLAlchemy ORM transformations (both normal and batch) as another way to further improve performance - with caveats~ -> EDIT: moved to #126 
- ~a main difference between the different types of transformations, is that Raw SQL and SQLAlchemy queries are ideal for table-to-table transformations, while SQLAlchemy ORM is the way to go if you want to read directly from file or have more complex processing steps, but records insertion will be significantly slower. Basically guiding a bit the user on what to use.. Anything else worth mentioning?~ -> EDIT: moved to #126 

If you like, I could pick up (some of) these points while writing the SQLAlchemy query part :)

2021-03-16 12:07 UTC, alepev commented
I also get this sphinx error, but it was there before.. Not sure how to fix it 🤔 
```
/Users/alessia/My_Installs/OHDSI_projects/ohdsi-etl-framework/delphyne/src/delphyne/database/database.py:docstring of src.delphyne.database.database.Database.reflected_metadata:1: WARNING: duplicate object description of src.delphyne.database.database.Database.reflected_metadata, other instance in reference, use :noindex: for one of them
/Users/alessia/My_Installs/OHDSI_projects/ohdsi-etl-framework/delphyne/src/delphyne/database/database.py:docstring of src.delphyne.database.database.Database.schemas:1: WARNING: duplicate object description of src.delphyne.database.database.Database.schemas, other instance in reference, use :noindex: for one of them
```

2021-03-31 08:15 UTC, alepev commented
> Still some changes, but much better!
> 
> Actually there are also couple big points I'm missing in the description (which I failed to bring up in the previous review 🤦‍♀️ ):
> 
> * ~we should mention the `bulk_mode` option in the SQLAlchemy ORM transformations (both normal and batch) as another way to further improve performance - with caveats~ -> EDIT: moved to #126
> * ~a main difference between the different types of transformations, is that Raw SQL and SQLAlchemy queries are ideal for table-to-table transformations, while SQLAlchemy ORM is the way to go if you want to read directly from file or have more complex processing steps, but records insertion will be significantly slower. Basically guiding a bit the user on what to use.. Anything else worth mentioning?~ -> EDIT: moved to #126
> 
> If you like, I could pick up (some of) these points while writing the SQLAlchemy query part :)

@MaximMoinat we had a more general issue for guiding the user on performance optimization (#126 ), I moved the two points above there so no need to add this now

2021-04-13 08:49 UTC, MaximMoinat commented on docs/transformations.rst
> +-------------
For me, it  still renders  fine though!

2021-04-13 08:53 UTC, MaximMoinat commented on docs/transformations.rst
> +-------------
According to these docs, it does not actually need to be the same length (or is it a local delphyne convention? 😝 )

https://docutils.sourceforge.io/docs/user/rst/quickref.html#section-structure

> Titles are underlined (**or over-
> and underlined**) with a printing
> nonalphanumeric 7-bit ASCII
> character.

2021-04-13 08:53 UTC, MaximMoinat commented on docs/transformations.rst
> +-------------
(still, I have updated all titles, does my OCD good...)

2021-04-13 09:39 UTC, MaximMoinat commented on docs/transformations.rst
> +In the wrapper these two transformations can be called like this:
@alepev Wait a minute, but the delphyne-template has these execute calls in the `transform()` method... 👀 
https://github.com/thehyve/delphyne-template/blob/master/src/main/python/wrapper.py

2021-04-13 09:40 UTC, MaximMoinat commented
Thanks again @alepev for the scrutinous review! Hope it passes the next :-)

2021-04-13 11:26 UTC, alepev commented on docs/transformations.rst
> +-------------
My bad, indeed it says "at least as long as".. can be longer. Sorry for being so strict 😅

2021-04-13 11:37 UTC, alepev commented on docs/transformations.rst
> +In the wrapper these two transformations can be called like this:
True, and in fact in a separate PR we are going to add a documentation page about delphyne-template, to better explain the user where exactly to add these calls. And then we will add a reference here and in other places with a link to the delphyne-template page describing how to implement the wrapper.run() method. I might also move some content around, depending on what looks more clear. For now it's ok like this :)

2021-04-13 13:01 UTC, MaximMoinat commented on docs/transformations.rst
> +-------------
I just realise that the highlighted comment about over/underlining is not relevant... Can you put the characters on top of the test as well (overlined)?

2021-04-13 13:03 UTC, MaximMoinat commented on docs/transformations.rst
> +In the wrapper these two transformations can be called like this:
Do we want to prescribe how to use the `run()` method? I think the only thing that is relevant is that this is the main entry point and the one method to implement when extending the class. Then how you organise your execute calls is totally up to you.

2021-04-13 13:36 UTC, alepev commented
review still in progress, but I will complete it today

2021-04-14 09:06 UTC, alepev commented on docs/readme.md
> +Then open `docs/_build/index.html` in your browser to preview the docs page.
good idea! but I suggest to add this as a new section in the main readme (root folder).
otherwise this can be mistaken for a source file for generating the docs themselves

2021-04-14 09:13 UTC, alepev commented on docs/transformations.rst
> +-------------
I also didn't know it was an option 🤔 anyway so far we have used underlined, so I wouldn't change it

2021-04-14 09:15 UTC, alepev reviewed
Well done, it reads smoothly now! Just a suggestion about the readme you added in the last round (see comments above). And then ready to merge

2021-04-14 09:16 UTC, alepev commented on docs/readme.md
> +Then open `docs/_build/index.html` in your browser to preview the docs page.
and beware of "projeeeeeeeeeeeect" :P

2021-04-14 09:37 UTC, alepev commented on docs/transformations.rst
> +**TBC**
```suggestion

.. code-block:: python

    def my_sql_transformation(wrapper):
    
        source_table = wrapper.cdm.<source_table>.__table__
        target_table = wrapper.cdm.<target_table>.__table__

        sel = select([
            source.columns['source_column_1'],
            source.columns['source_column_2'],
            ])\
            .select_from(source)

        ins = target.insert().from_select(sel.columns, sel)
        
        return ins
        
In case the source table is not part of the CDM schema, you can obtain it with the following method, which leverages SQLAlchemy's ability to create reflected table objects from the database itself:

.. code-block:: python
        source_table = wrapper.get_table(schema='my_source_schema', table_name='my_source_table')
        
Inside a wrapper method, the transformations can be called like this, similar to ORM transformations.

.. code-block:: python
    def run(self):
        ...
        self.execute_sql_transformation(my_sql_transformation)

```

2021-04-14 10:49 UTC, alepev commented
p.s. yesterday Stefan made some fixes that should resolve the build errors you see above, they probably have nothing to do with your changes (except perhaps for the linter error)

2021-04-15 12:10 UTC, alepev approved these changes
OK, I just added a small update from my side (I forgot the links to the wrapper code in the section about SQLAlchemy SQL queries). 
There are some warnings about Database method docstrings but they will disappear when merging to master

2021-04-15 13:31 UTC, merged